title: Yoogaaruna Priya Palanisamy

logo: /assests/img/photo_yooga_1.jpg

description:  Electrical and Electronics Engineer |ğŸ“ Kuala Lumpur, Malaysia | ğŸ“ 011-2325 9882 | ğŸ“§ pyooga28@gmail.com

#show_downloads: true

theme: jekyll-theme-minimal
